language: python
python:
  - "3.5"
services:
  - postgresql
before_script:
  - psql -c 'create database glassfrog_hipchat_test;' -U postgres
# command to install dependencies
install:
  - python3 setup.py install
  - pip install codecov
# command to run tests
script:
  - python3 tests/glassfrog_tests.py
  - coverage run tests/glassfrog_tests.py

after_success:
    codecov
